name: Go

on:
  workflow_dispatch:   # Allows you to manually trigger the workflow from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Output build success message
      run: echo "Build and tests passed successfully!"

    - name: Run APP
      run: go run .
